---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - id: japella
    dir: service
    main: main.go
    binary: japella
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64]
    ldflags:
      - -s -w -X buildinfo.Version={{.Version}} -X buildinfo.GitCommit={{.Commit}} -X buildinfo.BuildDate={{.Date}}

archives:
  - builds: [japella]

dockers:
  - id: japella
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/jamesread/japella
    extra_files:
      - README.md
      - webui
      - var/config-skel/

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
