configversion: 2

amqp:
  host: rabbitmq
  user: guest
  pass: guest
  port: 5672

database:
  host: mysql
  user: japella
  password: password
  database: japella


connectors:
  discord:
    appid: ""
    publickey: ""
    token: ""

  mastodon:
    register: true
    website: ""

  telegram:
    bottoken: ""
