FROM registry.fedoraproject.org/fedora-minimal:38-x86_64

LABEL org.opencontainers.image.source https://github.com/jamesread/japella

ADD japella-bot-watcher-prometheus /

ENTRYPOINT [ "/japella-bot-watcher-prometheus" ]
