---
site_name: Japella Docs
site_description: Documentation for Japella.
repo_url: https://github.com/jamesread/japella
repo_name: jamesread/japella

markdown_extensions:
  - codehilite
  - toc:
      permalink: true

theme:
  name: material
  language: en
  include_search_page: true
  search_index_only: true
  features:
    - search.suggest
    - search.highlight
    - search.share


plugins:
  - search:
  - minify:
      minify_html: true
  - tags:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jamesread/japella

    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@jamesread

    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/jamesreadtweets

nav:
  - Welcome: index.md
  - Getting Started: gettingStarted.md
  - Installation:
      - Introduction: installation/index.md
      - docker: installation/docker.md
      - docker-compose: installation/docker-compose.md
  - Adapters:
      - Introduction: adapters/index.md
      - Discord: adapters/discord.md
      - Telegram: adapters/telegram.md
