---
site_url: https://jamesread.github.io/Japella
site_name: Japella Docs
site_description: A chatbot, which is multi-protocol, powerful and highly resilient.
repo_url: https://github.com/jamesread/Japella
repo_name: jamesread/japella
edit_uri: edit/main/docs
strict: true

markdown_extensions:
  - codehilite
  - toc:
      permalink: true

theme:
  name: material
  language: en
  logo: logo.png
  favicon: logo.png
  include_search_page: true
  search_index_only: true
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.download
  palette:
    primary: blue
    accent: light-blue

  icon:
    repo: fontawesome/brands/github


plugins:
  - search:
  - social:
  - minify:
      minify_html: true
  - tags:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jamesread/japella

    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@jamesread

    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/jamesreadtweets

nav:
  - Welcome: index.md
  - Getting Started: gettingStarted.md
  - Installation:
      - docker: installation/docker.md
      - docker-compose: installation/docker-compose.md
  - Adapters:
      - Introduction: adapters/index.md
      - Discord: adapters/discord.md
      - Telegram: adapters/telegram.md
