// Code generated by "kod generate"; DO NOT EDIT.

package todo

// TodoBot is implemented by [TodoBotImpl],
// which can be mocked with [NewMockTodoBot].
type TodoBot interface {
	// Name is implemented by [TodoBotImpl.Name]
	Name() string
	// Start is implemented by [TodoBotImpl.Start]
	Start()
}
