---
name: "Build Snapshot"

on:
  - push
  - workflow_dispatch

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.23.0'
          cache: true

      - name: buf-setup
        uses: bufbuild/buf-setup-action@v1.28.1

      - name: grpc
        run: make -w grpc

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v4.2.0
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean --skip=docker
        env:
          GITHUB_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
