name: build docs

on:
  push:
    branches:
    - main
jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: Build docs to pretty HTML!
    steps:
    - name: Checkout code
      uses: actions/checkout@v3



	
    - name: Deploy docs
			uses: mhausenblas/mkdocs-deploy-gh-pages@master
			# Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
			env:
				GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
				# CUSTOM_DOMAIN: optionaldomain.com
				CONFIG_FILE: mkdocs.yml
				# EXTRA_PACKAGES: build-base
				# GITHUB_DOMAIN: github.myenterprise.com
				# REQUIREMENTS: folder/requirements.txt   - name: Get build container

